# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'testHomegate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testHomegate
  pod 'RealmSwift', '~>10.8.1'
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 6.0'

end
